### ISSUE TITLE
could not meet endorsement policy for chaincode

### ISSUE THREAD

**Issue by VolcanoWCAN** [kehm/ehrblockchainapplication#4]
Hi：
I meet another problem when I regsiter a new record. But I dont‘t how to deal with it.
I had started the network.
I added  the information to /etc/hosts. The information is:
172.18.0.40 peer0.hospital1.example.com
172.18.0.50 peer1.hospital1.example.com
172.18.0.60 peer0.pharmacy1.example.com
172.18.0.70 peer1.pharmacy1.example.com
172.18.0.80 peer0.practitioner1.example.com
172.18.0.90 peer1.practitioner1.example.com
172.18.0.100 orderer0.hospital1.example.com
172.18.0.110 orderer0.pharmacy1.example.com
172.18.0.120 orderer0.practitioner1.example.com

I can enroll successfully.
But  I cannot register the record.

Could you please give me some instruction？

The log outputs：
ERROR Channel - org.hyperledger.fabric.sdk.exception.ServiceDiscoveryException: Could not meet endorsement policy for chaincode RecordRelationshipContract
org.hyperledger.fabric.sdk.exception.ProposalException: org.hyperledger.fabric.sdk.exception.ServiceDiscoveryException: Could not meet endorsement policy for chaincode RecordRelationshipContract
	at org.hyperledger.fabric.sdk.Channel.sendTransactionProposalToEndorsers(Channel.java:3923)
	at com.example.hlfnetworkapplication.fabric.CommunicationHandler.transactionProposal(CommunicationHandler.java:155)
	at com.example.hlfnetworkapplication.javafx.InvokeService$1.call(InvokeService.java:38)
	at com.example.hlfnetworkapplication.javafx.InvokeService$1.call(InvokeService.java:35)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at javafx.concurrent.Service.lambda$executeTask$6(Service.java:725)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$7(Service.java:724)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.hyperledger.fabric.sdk.exception.ServiceDiscoveryException: Could not meet endorsement policy for chaincode RecordRelationshipContract
	at org.hyperledger.fabric.sdk.Channel.sendTransactionProposalToEndorsers(Channel.java:3917)
	... 11 more

**Comment by kehm** [comment]
The endorsement policy for each chaincode is specified in sample-setup/instantiate-chaincode.sh.
By default it is "OutOf(2, 'Hospital1MSP.peer', 'Pharmacy1MSP.peer', 'Practitioner1MSP.peer')", which means that at least 2 peers (from different organizations) must endorse the transaction successfully.

I would assume that your application is not communicating properly with the peers, which is why the endorsement fails. Check the docker logs of the peers to find out why they are not endorsing the transaction (or if they are receiving the endorsement request at all).

Also note the node types (client, peer, member etc.) and policies specified in configtx.yaml.
(if you disable EnableNodeOUs in crypto-config.yaml all entities are identified as .member).
